//	$Id: ctrl.h,v 1.3 2002/02/17 17:28:41 sugiura Exp $
/*
 *	ctrl.h
 *	コントロール名の定義＆汎用ヘッダ
 */

#if defined(DECLARE_CTRL_HEADER)&&defined(DECLARE_CTRL_CTRL)&&defined(DECLARE_CTRL_LAST)&&defined(DECLARE_CTRL_FOOTER)

DECLARE_CTRL_HEADER
	DECLARE_CTRL_CTRL(NULLCTRL)
	DECLARE_CTRL_CTRL(BUTTON)
	DECLARE_CTRL_CTRL(DEFBUTTON)
	DECLARE_CTRL_CTRL(REFFILEBUTTON)
	DECLARE_CTRL_CTRL(REFDIRBUTTON)
	DECLARE_CTRL_CTRL(REFCOLORBUTTON)
	DECLARE_CTRL_CTRL(REFFONTBUTTON)
	DECLARE_CTRL_CTRL(LIST)
	DECLARE_CTRL_CTRL(CHECK)
	DECLARE_CTRL_CTRL(RDBTN)
	DECLARE_CTRL_CTRL(RADIO)
	DECLARE_CTRL_CTRL(EDIT)
	DECLARE_CTRL_CTRL(MLEDIT)
	DECLARE_CTRL_CTRL(PWDEDIT)
	DECLARE_CTRL_CTRL(COMBO)
	DECLARE_CTRL_CTRL(CMBLIST)
	DECLARE_CTRL_CTRL(TEXT)
	DECLARE_CTRL_CTRL(SPIN)
	DECLARE_CTRL_CTRL(TRACK)
	DECLARE_CTRL_CTRL(HLINE)
	DECLARE_CTRL_CTRL(VLINE)
	DECLARE_CTRL_CTRL(TREE)
	DECLARE_CTRL_CTRL(LVIEW)
	DECLARE_CTRL_CTRL(CHKLIST)
	DECLARE_CTRL_CTRL(FRAME)
	DECLARE_CTRL_CTRL(GROUP)
	DECLARE_CTRL_CTRL(TAB)
	DECLARE_CTRL_CTRL(OKCANCEL)
	DECLARE_CTRL_CTRL(NEWPAGE)
	DECLARE_CTRL_CTRL(NEWCOLUMN)
	DECLARE_CTRL_LAST
DECLARE_CTRL_FOOTER

#endif
