//	$Id: str_tbl.h,v 1.2 2002-02-10 09:27:32 sugiura Exp $
/*
 *	str_tbl.h
 *	文字列テーブルの定義
 */

#ifndef	DENGAKUSERIES_FUNC_STR_TBL
#define	DENGAKUSERIES_FUNC_STR_TBL

#include "strbuf.h"

#define	WM_USER_SHOWUSERMENU	(WM_USER+1001)
#define	WM_USER_SHOWUSERDLG		(WM_USER+1002)
#define	WM_USER_MESSAGEBOX		(WM_USER+1003)
#define	WM_USER_QUESTIONBOX		(WM_USER+1004)
#define	WM_USER_NOTIFY			(WM_USER+1005)
#define WM_USER_GETFOCUSEDCTRL  (WM_USER+1006)
#define WM_USER_MAX				(WM_USER_GETFOCUSEDCTRL + 1)

#define	STR_HEAD						(-9)
#define	STR_UNKNOWNSTR					0
#define STR_VERSION						(STR_HEAD+10)
#define	STR_USRMSGBOX_MESSAGE			(STR_HEAD+11)
#define	STR_USRMSGBOX_QUESTION			(STR_HEAD+12)
#define	STR_DLGDATA_DLGFRAMEPROPERTY	(STR_HEAD+13)
#define	STR_DLGDATA_TITLE				(STR_HEAD+14)
#define	STR_DLGDATA_FONTSIZE			(STR_HEAD+15)
#define	STR_DLGDATA_FONTNAME			(STR_HEAD+16)
#define	STR_DLGDATA_PLACEX				(STR_HEAD+17)
#define	STR_DLGDATA_PLACEY				(STR_HEAD+18)
#define	STR_DLGDATA_WIDTH				(STR_HEAD+19)
#define	STR_DLGDATA_FLAGS				(STR_HEAD+20)
#define	STR_DLGDATA_PAGENAME			(STR_HEAD+21)
#define	STR_DLGDATA_PAGENUM				(STR_HEAD+22)
#define	STR_DLGDATA_DLGPAGEPROPERTY		(STR_HEAD+23)
#define	STR_DLGDATA_ENABLE				(STR_HEAD+24)
#define	STR_DLGDATA_CTRLNUM				(STR_HEAD+25)
#define	STR_DLGDATA_CTRLPROPERTY		(STR_HEAD+26)
#define	STR_DLGDATA_TYPE				(STR_HEAD+27)
#define	STR_DLGDATA_NAME				(STR_HEAD+28)
#define	STR_DLGDATA_TEXT				(STR_HEAD+29)
#define	STR_DLGDATA_ITEMNUM				(STR_HEAD+30)
#define	STR_DLGDATA_CHILD				(STR_HEAD+31)
#define	STR_DLGDATA_INTERNALCTRLNUM		(STR_HEAD+32)
#define	STR_DLGDATA_NOTIFY				(STR_HEAD+33)
#define	STR_DLGDATA_HEIGHT				(STR_HEAD+34)
#define	STR_DLGDATA_CTRL				(STR_HEAD+35)
#define	STR_DLGDATA_ID					(STR_HEAD+36)
#define	STR_DLGDATA_STATE				(STR_HEAD+37)
#define	STR_DLGDATA_MIN					(STR_HEAD+38)
#define	STR_DLGDATA_MAX					(STR_HEAD+39)
#define	STR_DLGDATA_VAL					(STR_HEAD+40)
#define	STR_DLGDATA_TIC					(STR_HEAD+41)
#define	STR_DLGDATA_ITEM				(STR_HEAD+42)
#define	STR_DLGDATA_COLNUM				(STR_HEAD+43)
#define	STR_DLGDATA_USEHEADER			(STR_HEAD+44)
#define	STR_DLGDATA_HEADER				(STR_HEAD+45)
#define	STR_DLGDATA_ROOT				(STR_HEAD+46)
#define	STR_DLGDATA_OK					(STR_HEAD+47)
#define	STR_DLGDATA_CANCEL				(STR_HEAD+48)
#define	STR_DLGDATA_REFBUTTON			(STR_HEAD+49)
#define	STR_DLGDATA_VERSION				(STR_HEAD+50)
#define	STR_DLGDATA_COMMONPROPERTY		(STR_HEAD+51)
#define	STR_DLGDATA_USERSIGNATURE		(STR_HEAD+52)
#define	STR_DLGDATA_STATES				(STR_HEAD+53)
#define	STR_DLGDATA_IMESTATE			(STR_HEAD+54)
#define	STR_LAST						(STR_HEAD+55)

extern	LPCSTR	const_strings[];

inline LPCSTR
GetString(WORD resid)
{
	return const_strings[(resid < STR_LAST) ? resid : STR_UNKNOWNSTR];
}

#endif
